version: "3.8"

services:
  app:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/find_it_auth_service
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=find_it_auth_service
    ports:
      - "5432:5432"
    restart: always